export const ExpensesCategoryLocators = {
  addNewExpenseCategoryButton: `(//button[@type='button'])[5]`,
  createExpenseCategoryContainer: `//div[@class='ant-drawer-content-wrapper']`,
  nameInput: `#name`,
  descriptionInput: `#description`,
  colorInput: `#color`,
  submitButton: `//button[@type='submit']`, 
  closeContainerButton: `.ant-drawer-close`,
  successToaster: `.ant-notification-notice-wrapper`,
  closeToasterButton: `.ant-notification-notice-close`,
  popupSpinner: `.ant-spin-spinning`,
  refreshButton: `(//div[@class='ant-space-item'])[2]`,
  expensesCategoryTable: `.ant-table-tbody`,
  refreshSpinner: `.ant-spin-dot.ant-spin-dot-spin`,
  titleToaster: `.ant-notification-notice-message`,
  descriptionToaster: `.ant-notification-notice-description`,
  searchInput: `Search`,
  threePointsButton: `ellipsis`,
  infoPopUp: `//div[@role='dialog']`,
  textValuePopUp: `//div[@class="ant-col ant-col-14 gutter-row css-1lk2pln"]/p`,
  removeButton: `Remove`,
  editButton: `Edit`,
  deleteConfirmationPopup: `/html/body/div[5]/div/div[2]/div/div[1]`,
  acceptRemoveButton: `/html/body/div[5]/div/div[2]/div/div[1]/div/div[3]/button[2]`,
  showOption: 'Show',
  removeOption: 'Delete'
};
